[build]
  command = "npm run build"
  publish = "site/public"

[[plugins]]
  package = "../plugin"
  [plugins.inputs]
    templateRepository = "https://github.com/jlengstorf/example-onboarding-flow.git"
    requiredEnvVars = ["REQUIRED_ENV_VAR", "BREAK_IT"]

[template.environment]
  REQUIRED_ENV_VAR = "A required env var"
  BREAK_IT = "Another required env var"
